#!/bin/bash
git add . #komanda "uzmanāmo" mapju pievienošana
git config --global user.name realarvis
git config --global user.email arvis010601@gmail.com
git commit -m "Class_05a"
git push origin main

